// ═══════════════════════════════════════════════════
// CORINA OS — DATABASE FILE
// 365 frases · Hábitos · Rutinas · Owners de contenido
// ═══════════════════════════════════════════════════

// ── 365 FRASES PARA 2026 (una por día, distribuidas) ──
const PHRASES_2026 = [
  // ENERO — Filosofía / Inicios
  {cat:'Filosofía',text:'El camino de los mil pasos comienza con un solo paso. Lo difícil no es empezar — es seguir.',author:'Lao Tzu'},
  {cat:'Matemática',text:'x₁ = x₀ + Δx. Todo cambio comienza con una pequeña diferencia sobre tu estado actual.',author:'Cálculo diferencial'},
  {cat:'Autorrealización',text:'No se trata de ser la mejor versión de alguien más. Se trata de convertirte en la mejor versión de vos misma.',author:'Brené Brown'},
  {cat:'Estoicismo',text:'Hoy es el único día que realmente tenés. Ayer es ficción, mañana es especulación.',author:'Marco Aurelio'},
  {cat:'Filosofía',text:'La excelencia no es un acto, es un hábito. Somos lo que hacemos repetidamente.',author:'Aristóteles'},
  {cat:'Física',text:'Un cuerpo en reposo tiende a seguir en reposo. Por eso el primer movimiento es el más importante.',author:'Primera Ley de Newton'},
  {cat:'Matemática',text:'El interés compuesto es la octava maravilla del mundo. Quien lo entiende, lo gana. Quien no, lo paga.',author:'Albert Einstein'},
  {cat:'Autorrealización',text:'La persona que piensas que eres limita lo que podés llegar a ser. Reescribí la historia.',author:'Carol Dweck'},
  {cat:'Filosofía',text:'No puedes bañarte dos veces en el mismo río. Vos tampoco sos la misma persona que empezó este camino.',author:'Heráclito'},
  {cat:'Ciencias',text:'Tu cerebro se reconfigura con cada nuevo hábito. Literalmente te reconstruís neurona por neurona.',author:'Neuroplasticidad'},

  // Semanas 2-3 Enero
  {cat:'Matemática',text:'Un 1% mejor cada día = 37x mejor al final del año. Un 1% peor cada día = 0.03x. La diferencia es exponencial.',author:'James Clear'},
  {cat:'Estoicismo',text:'No es lo que te sucede lo que te define, sino cómo respondés. El espacio entre estímulo y respuesta es tu libertad.',author:'Viktor Frankl'},
  {cat:'Filosofía',text:'Conocete a vos misma. Ese es el principio y el fin de toda sabiduría.',author:'Sócrates'},
  {cat:'Física',text:'La energía ni se crea ni se destruye — solo se transforma. Tu energía invertida en aprender nunca se pierde.',author:'Ley de conservación'},
  {cat:'Autorrealización',text:'El propósito no se encuentra — se construye, un pequeño acto diario a la vez.',author:'Viktor Frankl'},
  {cat:'Matemática',text:'P(éxito) = esfuerzo × tiempo × dirección. Cambiar cualquier variable cambia el resultado.',author:'Corina OS'},
  {cat:'Filosofía',text:'Primero domina el arte del silencio, luego aprendé a hablar. La mayoría lo hace al revés.',author:'Pitágoras'},
  {cat:'Ciencias',text:'Los sistemas complejos emergen de reglas simples repetidas. Tu vida compleja emerge de tus hábitos simples de hoy.',author:'Teoría de sistemas'},
  {cat:'Estoicismo',text:'Dividí el día en lo que controlás y lo que no. Enfocá toda tu energía en lo primero.',author:'Marco Aurelio'},
  {cat:'Matemática',text:'Fibonacci encontró belleza en la secuencia donde cada paso suma los dos anteriores. Así es el crecimiento real.',author:'Leonardo Fibonacci'},

  // Semana 4 Enero
  {cat:'Filosofía',text:'El hombre que mueve una montaña comienza cargando pequeñas piedras.',author:'Confucio'},
  {cat:'Autorrealización',text:'No necesitás permiso de nadie para empezar. La única autorización que cuenta es la tuya.',author:'Brené Brown'},
  {cat:'Física',text:'La gravedad no discrimina. Actúa igual sobre el hierro y el oro. La constancia tampoco discrimina.',author:'Corina OS'},
  {cat:'Matemática',text:'El número áureo φ ≈ 1.618 aparece en la naturaleza, el arte, la arquitectura. La belleza tiene estructura.',author:'Luca Pacioli'},
  {cat:'Estoicismo',text:'Memento mori: recordá que morirás. No como amenaza — como liberación de lo trivial.',author:'Séneca'},
  {cat:'Filosofía',text:'El conocimiento es la única riqueza que, al compartirse, se multiplica.',author:'Francis Bacon'},
  {cat:'Ciencias',text:'La resistencia no es enemigo del músculo — es el estímulo que lo hace crecer. En finanzas, en vida, aplica igual.',author:'Fisiología'},
  {cat:'Matemática',text:'Convergencia: una serie puede tener infinitos términos y aún sumar valor finito. Tus pequeños esfuerzos convergen.',author:'Análisis'},
  {cat:'Autorrealización',text:'La hacienda tranquila que imaginás no es un destino — es el resultado natural de quien te estás convirtiendo hoy.',author:'Corina OS'},
  {cat:'Filosofía',text:'Virtud no es lo que hacés cuando alguien mira. Es lo que hacés cuando nadie lo sabrá nunca.',author:'Kant'},
  {cat:'Estoicismo',text:'El tiempo perdido no puede recuperarse. Pero el tiempo que resta puede invertirse con mayor sabiduría.',author:'Marco Aurelio'},

  // FEBRERO — Disciplina / Consistencia
  {cat:'Matemática',text:'La probabilidad de un evento improbable aumenta con cada intento. No abandonés antes de que la curva cambie.',author:'Corina OS'},
  {cat:'Filosofía',text:'La diferencia entre quien sos y quien podés ser es lo que hacés en el presente.',author:'Aristóteles'},
  {cat:'Física',text:'La luz viaja sola, pero no por eso avanza menos. La soledad elegida no es debilidad.',author:'Corina OS'},
  {cat:'Autorrealización',text:'Si querés cambiar tu vida, cambiá tus hábitos. Si querés cambiar tus hábitos, cambiá tu identidad.',author:'James Clear'},
  {cat:'Ciencias',text:'La entropía aumenta en sistemas cerrados. Pero vos no sos cerrada — podés agregar energía al tuyo.',author:'2° Ley Termodinámica'},
  {cat:'Estoicismo',text:'La vida es corta. Lo único valioso es cómo la vivimos.',author:'Séneca'},
  {cat:'Matemática',text:'Una función continua puede parecer plana, pero si graficás 10 años, la pendiente se vuelve obvia.',author:'Cálculo'},
  {cat:'Filosofía',text:'El sufrimiento es transitorio. El aprendizaje es permanente.',author:'Nietzsche'},
  {cat:'Autorrealización',text:'Tus metas no tienen que ser realistas. Tu plan para alcanzarlas, sí.',author:'Corina OS'},
  {cat:'Ciencias',text:'Los átomos no "intentan" formar moléculas — simplemente siguen las reglas. Seguir reglas consistentes crea formas complejas.',author:'Química'},

  {cat:'Matemática',text:'Si ganás 10% anual reinvertido, duplicás capital cada 7 años. Regla del 72.',author:'Finanzas'},
  {cat:'Estoicismo',text:'No te enojes con las cosas — ellas no se dan cuenta.',author:'Marco Aurelio'},
  {cat:'Filosofía',text:'La paciencia es amarga, pero su fruto es dulce.',author:'Aristóteles'},
  {cat:'Física',text:'Fuerza = masa × aceleración. Aumentá la aceleración (velocidad de ejecución) y la fuerza crece.',author:'2° Ley Newton'},
  {cat:'Autorrealización',text:'Lo que no medís, no podés mejorarlo. Lo que no registrás, no podés medirlo.',author:'Peter Drucker'},
  {cat:'Ciencias',text:'El cerebro consume 20% de tu energía. Usalo bien.',author:'Neurología'},
  {cat:'Matemática',text:'Un óvalo perfecto no existe en la naturaleza — solo aproximaciones. La perfección es ilusión estadística.',author:'Corina OS'},
  {cat:'Filosofía',text:'No hay viento favorable para quien no sabe a qué puerto va.',author:'Séneca'},
  {cat:'Autorrealización',text:'La disciplina pesa gramos, el arrepentimiento pesa toneladas.',author:'Jim Rohn'},
  {cat:'Estoicismo',text:'Muy pocas cosas son necesarias para vivir una vida feliz. Todo está dentro tuyo.',author:'Marco Aurelio'},

  {cat:'Matemática',text:'Logaritmo: crecimiento lento al principio, rápido cuando acumulás base. Así funcionan las habilidades.',author:'Matemáticas'},
  {cat:'Filosofía',text:'El río pasó, pero el cauce queda. Tus hábitos son el cauce de tu vida.',author:'Corina OS'},
  {cat:'Física',text:'El universo tiende al equilibrio. Solo con trabajo constante mantenés un sistema fuera de él.',author:'Termodinámica'},
  {cat:'Autorrealización',text:'Compararte con otros te hace infeliz. Compararte con quien eras ayer te hace crecer.',author:'Corina OS'},
  {cat:'Estoicismo',text:'Cuidá tu integridad como tu posesión más valiosa. Sin ella no tenés nada.',author:'Epicteto'},
  {cat:'Ciencias',text:'El estrés crónico mata neuronas. La meditación las reconstruye.',author:'Neurociencia'},
  {cat:'Matemática',text:'La derivada es la pendiente del cambio. Hoy podés definir tu pendiente mañana.',author:'Cálculo'},
  {cat:'Filosofía',text:'El que tiene un porqué para vivir puede soportar casi cualquier cómo.',author:'Nietzsche'},

  // MARZO — Acción / Construcción
  {cat:'Matemática',text:'1.01^365 = 37.78. Mientras que 0.99^365 = 0.025. La diferencia entre mejorar o empeorar 1% diario.',author:'Efecto compuesto'},
  {cat:'Filosofía',text:'El viaje de mil millas comienza bajo los pies.',author:'Lao Tzu'},
  {cat:'Autorrealización',text:'Dejá de esperar el momento perfecto. Hacé el momento perfecto.',author:'Corina OS'},
  {cat:'Ciencias',text:'Un hábito tarda en promedio 66 días en volverse automático. No 21.',author:'Psicología UCL'},
  {cat:'Estoicismo',text:'La felicidad de tu vida depende de la calidad de tus pensamientos.',author:'Marco Aurelio'},
  {cat:'Física',text:'La velocidad sin dirección es caos. La dirección sin velocidad es estancamiento. Necesitás ambas.',author:'Vectores'},
  {cat:'Matemática',text:'Paradoja de Zenón: los pequeños pasos infinitos suman un todo finito. No subestimes lo pequeño.',author:'Zenón'},
  {cat:'Filosofía',text:'Somos lo que pensamos. Todo lo que somos surge de nuestros pensamientos.',author:'Buda'},
  {cat:'Autorrealización',text:'Lo que buscás también te busca a vos. Pero tenés que moverte hacia adelante.',author:'Rumi'},
  {cat:'Ciencias',text:'El sueño consolida memoria. 7.5 horas es la dosis mínima para aprender con eficiencia.',author:'Neurociencia'},

  {cat:'Matemática',text:'Ecuación diferencial: dy/dt = k·y significa crecimiento exponencial. Así crecen tus inversiones e ideas.',author:'EDO'},
  {cat:'Estoicismo',text:'Lo que impide la acción, avanza la acción. Lo que se interpone en el camino, se vuelve el camino.',author:'Marco Aurelio'},
  {cat:'Filosofía',text:'El que mira hacia afuera sueña. El que mira hacia adentro despierta.',author:'Jung'},
  {cat:'Física',text:'Sin fricción no hay movimiento útil. La resistencia es parte del avance, no su enemigo.',author:'Mecánica'},
  {cat:'Autorrealización',text:'Todo lo que siempre quisiste está del otro lado del miedo.',author:'George Addair'},
  {cat:'Ciencias',text:'La dopamina no se libera al llegar a la meta, sino al acercarse. El viaje es la recompensa.',author:'Neurobiología'},
  {cat:'Matemática',text:'En geometría, la recta más corta entre dos puntos es la línea. En la vida, rara vez.',author:'Corina OS'},
  {cat:'Filosofía',text:'No le temo al hombre que practicó 10.000 patadas una vez. Le temo al que practicó una patada 10.000 veces.',author:'Bruce Lee'},
  {cat:'Autorrealización',text:'Nadie puede hacerte sentir inferior sin tu consentimiento.',author:'Eleanor Roosevelt'},
  {cat:'Estoicismo',text:'Si algo está en tu poder, ¿para qué preocuparte? Si no lo está, ¿de qué sirve preocuparse?',author:'Séneca'},

  {cat:'Matemática',text:'Promedio geométrico < aritmético siempre. Por eso un 50% de ganancia y 50% de pérdida no te devuelve al inicio.',author:'Estadística'},
  {cat:'Filosofía',text:'Conócete, acéptate, supérate.',author:'San Agustín'},
  {cat:'Física',text:'La luz tarda 8 minutos en llegar del sol. Siempre estás viendo el pasado.',author:'Astrofísica'},
  {cat:'Autorrealización',text:'Tu zona de confort es donde tus sueños van a morir.',author:'Corina OS'},
  {cat:'Ciencias',text:'El ejercicio libera BDNF — la proteína que hace crecer tus neuronas. Mover el cuerpo hace crecer el cerebro.',author:'Neurobiología'},
  {cat:'Matemática',text:'Integral definida: el área bajo tu curva de esfuerzo diario es quién sos.',author:'Cálculo'},
  {cat:'Estoicismo',text:'Todo lo que nos molesta de los demás puede enseñarnos algo sobre nosotros mismos.',author:'Jung'},
  {cat:'Filosofía',text:'El ave canta no porque tenga respuestas, sino porque tiene una canción.',author:'Proverbio chino'},

  // ABRIL — Resiliencia / Propósito
  {cat:'Matemática',text:'Un modelo simple que funciona vence a un modelo complejo que falla. KISS principle.',author:'Ingeniería'},
  {cat:'Autorrealización',text:'No te preguntés qué necesita el mundo. Preguntate qué te hace sentir viva, y andá a hacer eso.',author:'Howard Thurman'},
  {cat:'Estoicismo',text:'La adversidad no es castigo — es preparación.',author:'Séneca'},
  {cat:'Ciencias',text:'El estrés eustrés (positivo) construye. El distrés destruye. La diferencia es tu percepción.',author:'Psicobiología'},
  {cat:'Filosofía',text:'En el medio de la dificultad reside la oportunidad.',author:'Einstein'},
  {cat:'Física',text:'El péndulo oscila porque debe. La volatilidad es inherente a todo sistema que se mueve.',author:'Física'},
  {cat:'Matemática',text:'Teorema del valor medio: entre dos puntos de tu vida hay al menos un instante donde la velocidad fue el promedio.',author:'Cálculo'},
  {cat:'Autorrealización',text:'La mediocridad es contagiosa. La excelencia también.',author:'Corina OS'},
  {cat:'Estoicismo',text:'Cada día, piensa como si hubieras muerto. Así vivirás intensamente.',author:'Marco Aurelio'},
  {cat:'Ciencias',text:'Los músculos crecen cuando descansás, no cuando entrenás. El crecimiento ocurre en el silencio.',author:'Fisiología'},

  {cat:'Filosofía',text:'La naturaleza dotó al hombre con dos oídos y una boca por una razón.',author:'Epicteto'},
  {cat:'Matemática',text:'Variabilidad = sigma². Alta varianza requiere más muestras para detectar tendencia. Paciencia estadística.',author:'Probabilidad'},
  {cat:'Física',text:'La presión crea diamantes — solo si el carbono resiste sin romperse.',author:'Geología'},
  {cat:'Autorrealización',text:'La persona más peligrosa es aquella que no teme perder lo que tiene.',author:'Corina OS'},
  {cat:'Estoicismo',text:'No tenés poder sobre lo que te sucede — pero sobre tu mente sí.',author:'Marco Aurelio'},
  {cat:'Ciencias',text:'Tu microbioma intestinal influye en tu estado de ánimo. Comer bien = pensar bien.',author:'Gastroenterología'},
  {cat:'Matemática',text:'El espacio vectorial tuyo se genera por tus decisiones. Cada "sí" define una nueva dimensión.',author:'Álgebra lineal'},
  {cat:'Filosofía',text:'La disciplina es el puente entre metas y logros.',author:'Jim Rohn'},
  {cat:'Autorrealización',text:'Nadie es tú. Eso es tu superpoder.',author:'Corina OS'},
  {cat:'Estoicismo',text:'Las dificultades fortalecen la mente, como el trabajo fortalece el cuerpo.',author:'Séneca'},

  {cat:'Matemática',text:'Teorema del límite central: muestras aleatorias convergen a la normal. Tu vida tiende a tu comportamiento promedio.',author:'Estadística'},
  {cat:'Ciencias',text:'La neuroplasticidad no tiene edad. Tu cerebro a los 80 puede aprender como a los 20, si lo usás.',author:'Neurología'},
  {cat:'Filosofía',text:'Sé la persona que tu perro piensa que sos.',author:'Anónimo'},
  {cat:'Física',text:'La entalpía mide energía total del sistema. Tu energía total incluye todo: dinero, vínculos, salud, tiempo.',author:'Termodinámica'},
  {cat:'Autorrealización',text:'El fracaso es información valiosa para quien sabe leerla.',author:'Ray Dalio'},
  {cat:'Estoicismo',text:'La vida es muy corta para pelear batallas que no ganás ni querés.',author:'Corina OS'},
  {cat:'Matemática',text:'La divergencia mide cuánto un campo se "expande" desde un punto. Tu impacto se mide igual.',author:'Cálculo vectorial'},
  {cat:'Filosofía',text:'Hay dos errores en el camino de la verdad: no recorrerlo todo, y no empezar.',author:'Buda'},

  // MAYO — Sistema / Flujo
  {cat:'Matemática',text:'El teorema de Pitágoras: siempre hay una tercera dimensión. En la vida, siempre hay una perspectiva más.',author:'Pitágoras'},
  {cat:'Autorrealización',text:'Cuidá tus pensamientos, se vuelven palabras. Cuidá tus palabras, se vuelven acciones. Cuidá tus acciones, se vuelven hábitos.',author:'Lao Tzu'},
  {cat:'Estoicismo',text:'Si querés ser rico, no añadas a tus posesiones — restá a tus deseos.',author:'Epicuro'},
  {cat:'Ciencias',text:'El oxígeno llega al músculo por difusión — un gradiente. Sin diferencia, no hay movimiento. Necesitás tensión productiva.',author:'Fisiología'},
  {cat:'Filosofía',text:'Aprende de ayer. Viví hoy. Soñá con mañana.',author:'Einstein'},
  {cat:'Física',text:'El calor fluye de lo caliente a lo frío. Las ideas fluyen de lo activo a lo pasivo. Sé activa.',author:'Termodinámica'},
  {cat:'Matemática',text:'Iteración: x_{n+1} = f(x_n). Cada día sos el resultado de aplicarte una función a vos misma.',author:'Matemática'},
  {cat:'Autorrealización',text:'Tu imaginación es la vista previa de las atracciones venideras de tu vida.',author:'Einstein'},
  {cat:'Estoicismo',text:'Amor fati: amá tu destino. Aceptá lo que sucede para transformarlo.',author:'Nietzsche'},
  {cat:'Ciencias',text:'La respiración controla al sistema nervioso autónomo. 4-7-8 calma. 6 respiraciones/min sincroniza corazón-cerebro.',author:'Neurobiología'},

  {cat:'Matemática',text:'La segunda derivada te dice si la curva acelera o desacelera. Estás acelerando en 2026.',author:'Cálculo'},
  {cat:'Filosofía',text:'Donde hay voluntad, hay camino.',author:'Proverbio inglés'},
  {cat:'Física',text:'En la mecánica cuántica, medir cambia el sistema. Observarte cambia quién sos.',author:'Principio de incertidumbre'},
  {cat:'Autorrealización',text:'La peor prisión es un corazón cerrado.',author:'Papa Juan Pablo II'},
  {cat:'Estoicismo',text:'No perdás el tiempo discutiendo qué debería ser un buen ser humano. Sé uno.',author:'Marco Aurelio'},
  {cat:'Ciencias',text:'El hipocampo procesa memoria espacial. Explorar nuevos lugares literalmente hace crecer tu cerebro.',author:'Neurobiología'},
  {cat:'Matemática',text:'Una serie armónica diverge, aunque sus términos tiendan a cero. Pequeños esfuerzos sostenidos suman infinito.',author:'Análisis'},
  {cat:'Filosofía',text:'La vida no se trata de encontrarte a vos misma. Se trata de crearte a vos misma.',author:'George Bernard Shaw'},
  {cat:'Autorrealización',text:'El verdadero viaje del descubrimiento no consiste en buscar nuevos paisajes, sino en tener nuevos ojos.',author:'Marcel Proust'},
  {cat:'Estoicismo',text:'Que la sabiduría sea tu pan, la moderación tu vestido, y el esfuerzo tu herramienta.',author:'Séneca'},

  {cat:'Matemática',text:'La optimización busca el mejor punto en un paisaje de posibilidades. Tu vida es una función a maximizar.',author:'Optimización'},
  {cat:'Ciencias',text:'Los procesos se vuelven automáticos cuando pasan del córtex prefrontal a los ganglios basales. La repetición crea libertad.',author:'Neurociencia'},
  {cat:'Filosofía',text:'Sólo una vida vivida al servicio de otros vale la pena.',author:'Einstein'},
  {cat:'Física',text:'La energía libre de Gibbs determina si un proceso ocurre. Alineá lo que querés con lo que el sistema favorece.',author:'Termodinámica'},
  {cat:'Autorrealización',text:'Dejá de pedir permiso. Si esperás a que alguien te autorice, nunca empezarás.',author:'Corina OS'},
  {cat:'Estoicismo',text:'Esperá lo peor, trabajá por lo mejor, aceptá lo que venga.',author:'Séneca'},
  {cat:'Matemática',text:'El campo vectorial de gradiente apunta al máximo crecimiento. Seguí tu gradiente de propósito.',author:'Cálculo'},
  {cat:'Filosofía',text:'Yo pienso, luego existo. Pero pienso con mis actos, no solo con mi cabeza.',author:'Descartes (reinterpretado)'},

  // JUNIO — Perseverancia
  {cat:'Filosofía',text:'El hierro oxida por falta de uso. El estancamiento del agua pierde su pureza. Así con la inactividad drena el vigor.',author:'Leonardo da Vinci'},
  {cat:'Matemática',text:'La transformada de Fourier descompone señales complejas en simples. Descomponé tu vida en hábitos básicos.',author:'Fourier'},
  {cat:'Autorrealización',text:'Todo lo que existe fue una vez una idea en la mente de alguien.',author:'Corina OS'},
  {cat:'Ciencias',text:'El cortisol crónico daña el hipocampo. Meditar, dormir y socializar lo reparan.',author:'Neuroendocrinología'},
  {cat:'Estoicismo',text:'Si parece estar fuera de tu control, no te preocupés por él.',author:'Epicteto'},
  {cat:'Física',text:'Resonancia: pequeñas fuerzas sincronizadas generan amplitudes enormes. Alineate con tu ritmo interno.',author:'Mecánica ondulatoria'},
  {cat:'Matemática',text:'Una recursión que no converge diverge. Tus pensamientos recursivos: ¿hacia dónde van?',author:'Ciencias computación'},
  {cat:'Filosofía',text:'La meditación no es escape — es encuentro contigo misma.',author:'Thich Nhat Hanh'},
  {cat:'Autorrealización',text:'Si no diseñás tu vida, alguien más lo hará por vos.',author:'Jim Rohn'},
  {cat:'Estoicismo',text:'No hay nada permanente, excepto el cambio.',author:'Heráclito'},

  {cat:'Matemática',text:'El ratio de Sharpe mide retorno por unidad de riesgo. La vida bien vivida tiene alto Sharpe: alto retorno con riesgo controlado.',author:'Finanzas'},
  {cat:'Ciencias',text:'Los telómeros miden tu edad celular. El estrés los acorta. La meditación los alarga.',author:'Biología molecular'},
  {cat:'Filosofía',text:'La educación es el arma más poderosa para cambiar el mundo.',author:'Nelson Mandela'},
  {cat:'Física',text:'Campo magnético: las líneas nunca se cortan. Tus decisiones crean líneas que te llevan.',author:'Electromagnetismo'},
  {cat:'Autorrealización',text:'La peor sensación del mundo es saber que no diste lo mejor de vos.',author:'Corina OS'},
  {cat:'Estoicismo',text:'Soltá el resultado. Enfocate en la acción correcta. Los resultados cuidan de sí mismos.',author:'Bhagavad Gita'},
  {cat:'Matemática',text:'Grafo conexo: todos los nodos se pueden alcanzar. Conectá tus hábitos — uno lleva al otro.',author:'Teoría de grafos'},
  {cat:'Filosofía',text:'La sabiduría empieza en la maravilla.',author:'Sócrates'},
  {cat:'Autorrealización',text:'Tus creencias se convierten en tu destino.',author:'Gandhi'},
  {cat:'Ciencias',text:'Un fotón atraviesa el universo sin experimentar el tiempo. La velocidad más alta es atemporal.',author:'Relatividad'},

  {cat:'Matemática',text:'Una matriz identidad no cambia lo que multiplica. Sé tu propia constante en un mundo cambiante.',author:'Álgebra lineal'},
  {cat:'Filosofía',text:'Quien no se mueve, no nota las cadenas.',author:'Rosa Luxemburgo'},
  {cat:'Estoicismo',text:'La filosofía no promete riqueza, honor ni salud. Promete algo más valioso: la libertad interior.',author:'Epicteto'},
  {cat:'Ciencias',text:'Los axones se mielinizan con la repetición. Literalmente construís superautopistas neuronales con cada práctica.',author:'Neurología'},
  {cat:'Matemática',text:'Teorema fundamental del cálculo: la suma de tus infinitesimales es tu totalidad. Los pequeños momentos definen todo.',author:'Cálculo'},
  {cat:'Autorrealización',text:'No busques el éxito — buscá ser valiosa, y el éxito te perseguirá.',author:'Einstein'},
  {cat:'Física',text:'La gravedad curva el espacio-tiempo. Las grandes decisiones curvan tu línea de vida.',author:'Relatividad general'},
  {cat:'Filosofía',text:'La paciencia es un árbol de raíces amargas pero frutos dulces.',author:'Proverbio persa'},

  // JULIO — Transformación
  {cat:'Matemática',text:'Dimensión fractal: las formas complejas tienen dimensiones no enteras. Tu vida tampoco encaja en cajas simples.',author:'Mandelbrot'},
  {cat:'Ciencias',text:'El músculo atrófico se recupera con sobrecarga progresiva. Aplicá el principio a tu mente.',author:'Fisiología'},
  {cat:'Filosofía',text:'No hay camino hacia la felicidad; la felicidad es el camino.',author:'Buda'},
  {cat:'Estoicismo',text:'Considerá de día en día como una vida entera.',author:'Séneca'},
  {cat:'Autorrealización',text:'No perseguís resultados — perseguís hábitos.',author:'James Clear'},
  {cat:'Física',text:'La conductividad depende del material. Algunos transmiten mejor. Sé conductor de cosas buenas.',author:'Física de materiales'},
  {cat:'Matemática',text:'El análisis dimensional verifica ecuaciones. Verificá si lo que hacés hoy tiene las dimensiones de quien querés ser.',author:'Física aplicada'},
  {cat:'Filosofía',text:'La verdad es el espejo que se quiebra en mil pedazos. Cada uno cree tener la imagen completa.',author:'Rumi'},
  {cat:'Autorrealización',text:'No necesitás ser excelente para empezar, pero necesitás empezar para ser excelente.',author:'Zig Ziglar'},
  {cat:'Estoicismo',text:'La autocomplacencia es el mayor peligro que podemos enfrentar.',author:'Warren Buffett'},

  {cat:'Matemática',text:'Distribución normal: 68% de los datos están a 1 desviación de la media. Pero los cambios de vida ocurren en las colas.',author:'Estadística'},
  {cat:'Ciencias',text:'El hambre no es bueno para decidir. El cerebro consume glucosa al tomar decisiones difíciles.',author:'Neurobiología'},
  {cat:'Filosofía',text:'El hombre más rico es el que sabe el valor de las cosas simples.',author:'Aristóteles'},
  {cat:'Autorrealización',text:'Tu red de contactos es tu valor neto.',author:'Porter Gale'},
  {cat:'Estoicismo',text:'Cuando haces lo correcto, no importa lo que los demás piensen.',author:'Marco Aurelio'},
  {cat:'Física',text:'El universo se expande — pero algunas cosas (como la galaxia) se mantienen unidas por gravedad local. Tus vínculos son tu gravedad.',author:'Cosmología'},
  {cat:'Matemática',text:'Teoría del caos: pequeñas variaciones iniciales producen resultados radicalmente distintos. Tus decisiones de hoy cambian todo.',author:'Edward Lorenz'},
  {cat:'Filosofía',text:'El más grande error que podés cometer en la vida es tener miedo a cometer uno.',author:'Elbert Hubbard'},
  {cat:'Autorrealización',text:'Aprendé a estar sola. Nunca estarás sola si te caés bien a vos misma.',author:'Corina OS'},
  {cat:'Estoicismo',text:'Tus emociones son información, no instrucciones.',author:'Marco Aurelio (reinterpretado)'},

  {cat:'Matemática',text:'Derivada parcial: el cambio de una función respecto a una variable manteniendo las demás. Aislá una cosa a optimizar por vez.',author:'Cálculo multivariable'},
  {cat:'Ciencias',text:'El VO₂ máx mide capacidad aeróbica. Es uno de los mejores predictores de longevidad.',author:'Medicina deportiva'},
  {cat:'Filosofía',text:'La mente es una llama para mantener, no un recipiente para llenar.',author:'Plutarco'},
  {cat:'Física',text:'El momento angular se conserva. Cuando cerrás los brazos, girás más rápido. Concentrar energía acelera el cambio.',author:'Mecánica'},
  {cat:'Autorrealización',text:'No compitas con nadie más que contigo misma. Es la única batalla que podés ganar siempre.',author:'Corina OS'},
  {cat:'Estoicismo',text:'El hombre es perturbado no por los hechos, sino por sus opiniones de los hechos.',author:'Epicteto'},
  {cat:'Matemática',text:'Un sistema lineal es predecible. La vida es no lineal — y por eso apasiona.',author:'Dinámica de sistemas'},
  {cat:'Filosofía',text:'Nunca te rindas con alguien que amás, incluso si esa persona sos vos misma.',author:'Corina OS'},

  // AGOSTO — Estrategia
  {cat:'Matemática',text:'El criterio de Kelly optimiza crecimiento a largo plazo sin quebrar. Nunca apostés todo en una sola jugada.',author:'John Kelly'},
  {cat:'Ciencias',text:'La insulina crónicamente alta causa resistencia. Lo mismo con el placer: la dopamina baja cuando la buscás siempre.',author:'Endocrinología'},
  {cat:'Filosofía',text:'El hombre prudente busca amigos en la prosperidad para tenerlos en la desgracia.',author:'Gracián'},
  {cat:'Autorrealización',text:'El dinero compra libertad solo si sabés para qué querés esa libertad.',author:'Corina OS'},
  {cat:'Estoicismo',text:'No actúes sin haber deliberado; pero una vez deliberado, actúa con decisión.',author:'Marco Aurelio'},
  {cat:'Física',text:'Un sistema en equilibrio estable vuelve al equilibrio tras una perturbación. Un sistema inestable, no. Construí estabilidad.',author:'Mecánica'},
  {cat:'Matemática',text:'Funciones periódicas: lo que parece repetitivo en tu vida es ritmo — puede ser tu fortaleza o tu cárcel.',author:'Trigonometría'},
  {cat:'Filosofía',text:'La justicia es tomar un hábito de hacer lo que corresponde. Hace carácter.',author:'Aristóteles'},
  {cat:'Autorrealización',text:'Invertí en vos misma. Tu carrera es tu mejor activo.',author:'Warren Buffett'},
  {cat:'Estoicismo',text:'La felicidad depende de nosotros mismos.',author:'Aristóteles'},

  {cat:'Matemática',text:'El interés compuesto reversible: lo que gasta poco a poco, cuesta exponencial a largo plazo.',author:'Finanzas personales'},
  {cat:'Ciencias',text:'La melatonina se produce en oscuridad. Luces de pantalla a la noche = mal sueño = peor decisión.',author:'Cronobiología'},
  {cat:'Filosofía',text:'Cuanto más sé, más sé que no sé nada.',author:'Sócrates'},
  {cat:'Física',text:'La fuerza centrípeta mantiene el giro. Sin centro, no hay órbita. Tu propósito es tu centro.',author:'Mecánica'},
  {cat:'Autorrealización',text:'El lujo no es tener mucho, sino no tener que pedir permiso.',author:'Corina OS'},
  {cat:'Estoicismo',text:'No te ofendas por el comportamiento de otros. Ellos también están luchando.',author:'Marco Aurelio'},
  {cat:'Matemática',text:'Una gráfica logarítmica aplasta crecimientos exponenciales. A veces la escala correcta revela la verdad.',author:'Matemáticas aplicadas'},
  {cat:'Filosofía',text:'El objetivo de la vida es hacer tus latidos coincidir con los del universo.',author:'Joseph Campbell'},
  {cat:'Autorrealización',text:'El mejor momento para plantar un árbol fue hace 20 años. El segundo mejor momento es ahora.',author:'Proverbio chino'},
  {cat:'Estoicismo',text:'Sos la suma de tus actos. Actuá en consecuencia.',author:'Jean-Paul Sartre'},

  {cat:'Matemática',text:'Un modelo predictivo nunca es la realidad — solo una aproximación útil. Tu autoimagen también.',author:'Estadística'},
  {cat:'Ciencias',text:'El ayuno intermitente activa la autofagia: las células limpian sus desechos. A veces menos es más.',author:'Biología celular'},
  {cat:'Filosofía',text:'La libertad es el derecho a no mentir.',author:'Albert Camus'},
  {cat:'Física',text:'La luz se refracta al cambiar de medio. Cuando cambiás de entorno, tu trayectoria cambia.',author:'Óptica'},
  {cat:'Autorrealización',text:'Todos los éxitos se construyeron en los fracasos de alguien.',author:'Corina OS'},
  {cat:'Estoicismo',text:'El destino guía al que se deja guiar, arrastra al que se resiste.',author:'Cleantes'},
  {cat:'Matemática',text:'Un espacio de Hilbert puede tener infinitas dimensiones. Tu potencial también.',author:'Análisis funcional'},
  {cat:'Filosofía',text:'Cuidá los pequeños gastos; una pequeña fuga hunde un gran barco.',author:'Benjamin Franklin'},

  // SEPTIEMBRE — Precisión
  {cat:'Matemática',text:'Análisis de regresión: y = mx + b. Los patrones ocultos se revelan cuando recopilás suficientes datos.',author:'Estadística'},
  {cat:'Autorrealización',text:'Querer algo y obtenerlo son dos cosas distintas. El puente entre ambas se llama sistema.',author:'Scott Adams'},
  {cat:'Estoicismo',text:'Al principio, podés sentir que hacés poco. Al final, te sorprendás de todo lo logrado.',author:'Marco Aurelio'},
  {cat:'Ciencias',text:'La glucosa alta daña vasos sanguíneos. La dieta afecta tus decisiones antes de que lo notés.',author:'Medicina'},
  {cat:'Filosofía',text:'El que lee mucho y anda mucho, ve mucho y sabe mucho.',author:'Cervantes'},
  {cat:'Física',text:'Toda acción tiene reacción. Tu contexto responde a tus hábitos. Cambialo cambiando.',author:'3° Ley Newton'},
  {cat:'Matemática',text:'Un espacio métrico define distancia. ¿Qué distancia medís? ¿Dinero, tiempo, amor, propósito?',author:'Topología'},
  {cat:'Filosofía',text:'La libertad no es la ausencia de reglas. Es la disciplina de las correctas.',author:'Corina OS'},
  {cat:'Autorrealización',text:'Dejá de intentar motivarte. Construí sistemas que funcionen sin motivación.',author:'Scott Adams'},
  {cat:'Estoicismo',text:'Perder te enseña. Ganar te confirma.',author:'Corina OS'},

  {cat:'Matemática',text:'La probabilidad condicional cambia con nueva información. Mantenete flexible. Tu plan de hace 5 años no es tu plan de hoy.',author:'Teorema de Bayes'},
  {cat:'Ciencias',text:'Tu cerebro usa 20 watts. Menos que un foco LED. Potencia enorme por vatio.',author:'Neurociencia'},
  {cat:'Filosofía',text:'Sé formal en las apariencias y libre en los pensamientos.',author:'Confucio'},
  {cat:'Física',text:'La osmosis mueve agua hacia donde hay más sal. Las ideas migran hacia donde hay más contexto para comprenderlas.',author:'Biofísica'},
  {cat:'Autorrealización',text:'Perdoná, pero no olvidés. Los patrones se repiten.',author:'Corina OS'},
  {cat:'Estoicismo',text:'Todo lo que escuches, creélo la mitad. Todo lo que veas, creélo un cuarto.',author:'Ibn al-Jawzi'},
  {cat:'Matemática',text:'La regla del 3 sigma: 99.7% de eventos normales están cerca de la media. Los extremos son raros pero existen.',author:'Estadística'},
  {cat:'Filosofía',text:'Enseña lo que sabés, comparte lo que tenés, ayudá con lo que podés.',author:'Proverbio africano'},
  {cat:'Autorrealización',text:'La riqueza se mide en tiempo, no en dinero.',author:'Corina OS'},
  {cat:'Estoicismo',text:'No hay nada más grande que una mente ordenada.',author:'Marco Aurelio'},

  {cat:'Matemática',text:'Un juego de suma no cero: cooperar crea valor que la competencia destruye.',author:'Teoría de juegos'},
  {cat:'Ciencias',text:'Las mitocondrias eran bacterias independientes. La cooperación creó vida compleja. Solos llegamos rápido; juntas llegamos lejos.',author:'Biología evolutiva'},
  {cat:'Filosofía',text:'Si querés felicidad por una hora, dormí una siesta. Si la querés por un día, pescá. Si la querés para siempre, ayudá a alguien.',author:'Proverbio chino'},
  {cat:'Física',text:'Los agujeros negros tienen horizonte: un punto de no retorno. Identificá tus horizontes antes de cruzarlos.',author:'Relatividad'},
  {cat:'Autorrealización',text:'Tu red determina tu destino. Rodeate de quien querés ser.',author:'Corina OS'},
  {cat:'Estoicismo',text:'Antes de decir algo, preguntate: ¿es verdad? ¿es necesario? ¿es amable?',author:'Sócrates'},
  {cat:'Matemática',text:'Un hash criptográfico es irreversible: fácil computar, imposible deshacer. Algunas decisiones son así.',author:'Criptografía'},
  {cat:'Filosofía',text:'La paz no es la ausencia de conflicto, sino la presencia de justicia.',author:'Martin Luther King'},

  // OCTUBRE — Madurez
  {cat:'Matemática',text:'Un proceso estocástico tiene memoria. Tu historia personal influye el paso siguiente. Pero vos elegís cómo influye.',author:'Probabilidad'},
  {cat:'Ciencias',text:'El testosterona baja con sueño corto. La decisión también baja. Dormí.',author:'Endocrinología'},
  {cat:'Filosofía',text:'La paciencia es una virtud, pero la perseverancia es poder.',author:'Corina OS'},
  {cat:'Física',text:'La fricción genera calor. Todo esfuerzo genera energía interna. Aprovechala.',author:'Termodinámica'},
  {cat:'Autorrealización',text:'La única persona que tenés que ser mejor que la de ayer.',author:'Corina OS'},
  {cat:'Estoicismo',text:'Nada te pertenece excepto el tiempo.',author:'Séneca'},
  {cat:'Matemática',text:'El algoritmo greedy elige el mejor paso local. Pero a veces ceder localmente gana globalmente.',author:'Ciencias computación'},
  {cat:'Filosofía',text:'Las personas sabias hablan porque tienen algo que decir. Las necias, porque tienen que decir algo.',author:'Platón'},
  {cat:'Autorrealización',text:'Convertí tu herida en sabiduría.',author:'Oprah Winfrey'},
  {cat:'Estoicismo',text:'Cuidá tu tiempo como tu oro: raramente lo recuperás.',author:'Benjamin Franklin'},

  {cat:'Matemática',text:'Una función biyectiva es invertible. Hay decisiones reversibles y no. Sabé distinguirlas antes de actuar.',author:'Teoría de conjuntos'},
  {cat:'Ciencias',text:'El nervio vago conecta cerebro-intestino. Respirá profundo para activarlo. Calma instantánea.',author:'Neurobiología'},
  {cat:'Filosofía',text:'Sé el cambio que querés ver en el mundo.',author:'Gandhi'},
  {cat:'Física',text:'Los imanes tienen polos: se atraen o repelen. En las relaciones lo mismo. Identificá la polaridad antes de esforzarte.',author:'Electromagnetismo'},
  {cat:'Autorrealización',text:'El minimalismo no es tener menos — es dar espacio a lo que importa.',author:'Corina OS'},
  {cat:'Estoicismo',text:'No busqués seguridad en tus pertenencias. Busca seguridad en tu juicio.',author:'Séneca'},
  {cat:'Matemática',text:'Fractales: complejidad infinita desde reglas finitas. Tu vida es fractal.',author:'Geometría fractal'},
  {cat:'Filosofía',text:'La vida es la que pasa mientras hacés otros planes.',author:'John Lennon'},
  {cat:'Autorrealización',text:'Si cambiás la forma en que mirás las cosas, las cosas que mirás cambian.',author:'Wayne Dyer'},
  {cat:'Estoicismo',text:'La vida es como un camino entre espinas: si la recorrés enojada, sangrás más.',author:'Séneca'},

  {cat:'Matemática',text:'El teorema de Gödel: hay verdades indemostrables dentro de cualquier sistema. Algunas cosas solo se saben.',author:'Kurt Gödel'},
  {cat:'Ciencias',text:'El ciclo circadiano dicta hormonas. Desalinearlo = cansancio crónico. Respetá tu reloj.',author:'Cronobiología'},
  {cat:'Filosofía',text:'Una onza de práctica vale más que una tonelada de prédica.',author:'Gandhi'},
  {cat:'Física',text:'La gravedad de un cuerpo depende de su masa. Las personas significativas tienen "masa propia". Sé una de ellas.',author:'Metáfora newtoniana'},
  {cat:'Autorrealización',text:'Lo opuesto al amor no es el odio — es la indiferencia.',author:'Elie Wiesel'},
  {cat:'Estoicismo',text:'No necesitás más tiempo — necesitás decidir qué hacer con el que tenés.',author:'Séneca'},
  {cat:'Matemática',text:'Grafos de pequeño mundo: cualquier persona está a 6 saltos de cualquier otra. Tu red es más grande de lo que pensás.',author:'Redes sociales'},
  {cat:'Filosofía',text:'Toda gran travesía comienza con el coraje de decir sí a lo desconocido.',author:'Corina OS'},

  // NOVIEMBRE — Cosecha
  {cat:'Matemática',text:'Un algoritmo de búsqueda binaria encuentra en log₂(n) pasos. Buscá con estrategia, no con fuerza bruta.',author:'Computación'},
  {cat:'Ciencias',text:'El proprioceptor te dice dónde está tu cuerpo. La introspección es el proprioceptor del alma.',author:'Neurociencia'},
  {cat:'Filosofía',text:'El mejor maestro es el tiempo. El peor también.',author:'Corina OS'},
  {cat:'Física',text:'El efecto mariposa: condiciones iniciales determinan el futuro. Tus hábitos de ahora determinan tu 2030.',author:'Teoría del caos'},
  {cat:'Autorrealización',text:'Dejá de querer ser la versión que otros necesitan. Sé la versión que vos necesitás.',author:'Corina OS'},
  {cat:'Estoicismo',text:'El objetivo principal de la vida no es la felicidad, sino la virtud. La felicidad es un derivado.',author:'Aristóteles'},
  {cat:'Matemática',text:'El límite es un concepto: nunca alcanzado, siempre aproximado. Perseguir la perfección es vano; perseguir la excelencia es útil.',author:'Cálculo'},
  {cat:'Filosofía',text:'La riqueza no consiste en tener grandes posesiones, sino en tener pocas necesidades.',author:'Epicuro'},
  {cat:'Autorrealización',text:'Nunca envejecen los sueños — solo sus soñadores.',author:'Corina OS'},
  {cat:'Estoicismo',text:'Los días pasan rápidos. Las semanas pasan rápidas. Los años no.',author:'Corina OS'},

  {cat:'Matemática',text:'La mediana resiste a outliers. El promedio no. En valoraciones personales, confiá en la mediana.',author:'Estadística'},
  {cat:'Ciencias',text:'El cortisol mañanero te activa. Si pasás todo el día estresada, lo gastás temprano.',author:'Endocrinología'},
  {cat:'Filosofía',text:'La vida bien vivida es larga.',author:'Séneca'},
  {cat:'Física',text:'El agua hierve a 100°C, pero necesita energía constante para llegar ahí. Tu punto de ebullición existe.',author:'Termodinámica'},
  {cat:'Autorrealización',text:'Dormí. Tomá agua. Respirá. Movete. Leé. Amá. Repetí.',author:'Corina OS'},
  {cat:'Estoicismo',text:'Considerate ya muerta. Ahora vivís tiempo regalado.',author:'Marco Aurelio'},
  {cat:'Matemática',text:'Un número primo solo es divisible por 1 y por sí mismo. Sé indivisible.',author:'Teoría de números'},
  {cat:'Filosofía',text:'Conocer a otros es inteligencia. Conocerte a vos misma es sabiduría.',author:'Lao Tzu'},
  {cat:'Autorrealización',text:'El éxito no es final, el fracaso no es fatal: es el coraje de continuar lo que cuenta.',author:'Churchill'},
  {cat:'Estoicismo',text:'La mejor venganza es ser lo que ellos dicen que no podés ser.',author:'Corina OS'},

  {cat:'Matemática',text:'Un cuaternión describe rotaciones 3D sin singularidades. Algunos problemas necesitan dimensiones extra para resolverse.',author:'Hamilton'},
  {cat:'Ciencias',text:'El acetilcolina mejora foco. La dopamina, motivación. El GABA, calma. Química de la productividad.',author:'Neurofarmacología'},
  {cat:'Filosofía',text:'Si buscás perfección, jamás estarás satisfecha.',author:'Leo Tolstói'},
  {cat:'Física',text:'La entropía del universo aumenta — excepto en los sistemas donde invertís energía para ordenar. Tu vida es uno.',author:'Termodinámica'},
  {cat:'Autorrealización',text:'La hacienda no es un lugar físico — es la paz que llevás con vos a donde vayás.',author:'Corina OS'},
  {cat:'Estoicismo',text:'Por cada adversidad, una oportunidad equivalente o mayor.',author:'Napoleon Hill'},
  {cat:'Matemática',text:'Un grupo de Lie es continuo y simétrico. Las transformaciones suaves crean estructura.',author:'Álgebra avanzada'},
  {cat:'Filosofía',text:'Lo que se da al corazón, nunca se pierde.',author:'Proverbio irlandés'},

  // DICIEMBRE — Reflexión / Cierre
  {cat:'Matemática',text:'Una esperanza matemática es un promedio ponderado. La vida que esperás depende de cuánto peso das a cada opción.',author:'Probabilidad'},
  {cat:'Ciencias',text:'El cerebro consolida aprendizajes durante REM. Dormir mal = aprender mal.',author:'Neurociencia'},
  {cat:'Filosofía',text:'En el fondo de nuestra alma hay un fuego que solo nosotros podemos encender.',author:'Rumi'},
  {cat:'Física',text:'El principio de incertidumbre: no podés medir posición y velocidad exactas simultáneamente. Aceptá la ambigüedad.',author:'Heisenberg'},
  {cat:'Autorrealización',text:'Tu mayor responsabilidad es hacia vos misma. Si fallás con vos, fallás con todos.',author:'Corina OS'},
  {cat:'Estoicismo',text:'La vida no es ni buena ni mala. Es lo que hacés con ella.',author:'Séneca'},
  {cat:'Matemática',text:'El coeficiente de correlación no implica causalidad. Un patrón no siempre es la razón.',author:'Estadística'},
  {cat:'Filosofía',text:'Cuando nada es cierto, todo es posible.',author:'Margaret Drabble'},
  {cat:'Autorrealización',text:'Cuando mirés atrás dentro de 10 años, ¿qué hábito de hoy vas a agradecer?',author:'Corina OS'},
  {cat:'Estoicismo',text:'Hoy fue un buen día. Mañana también lo será. La calidad la ponés vos.',author:'Séneca'},

  {cat:'Matemática',text:'Una matriz simétrica tiene autovalores reales. Las relaciones recíprocas son medibles.',author:'Álgebra'},
  {cat:'Ciencias',text:'Las células se regeneran cada 7 años. Literalmente sos una persona nueva.',author:'Biología'},
  {cat:'Filosofía',text:'Lo mejor de la vida son las cosas gratuitas: conversaciones, caminatas, risas, silencios.',author:'Corina OS'},
  {cat:'Física',text:'Toda energía viene en paquetes discretos: cuantos. La vida también — avanzá de cuanto en cuanto.',author:'Mecánica cuántica'},
  {cat:'Autorrealización',text:'No hay plan B. Porque el plan B distrae del plan A.',author:'Will Smith'},
  {cat:'Estoicismo',text:'Lo que logramos en el interior cambia la realidad exterior.',author:'Plutarco'},
  {cat:'Matemática',text:'El principio de dualidad: cada estructura tiene una dual. Cada fortaleza trae su debilidad. Conocé ambas.',author:'Álgebra lineal'},
  {cat:'Filosofía',text:'El pensamiento es el trabajo más difícil que existe. Quizás por eso pocos se dedican a él.',author:'Henry Ford'},
  {cat:'Autorrealización',text:'Al final del año sos exactamente la suma de tus decisiones pequeñas.',author:'Corina OS'},
  {cat:'Estoicismo',text:'La mente tiñe el alma con el color de sus pensamientos.',author:'Marco Aurelio'},

  // Diciembre final
  {cat:'Matemática',text:'Un bucle cerrado retroalimenta. Un bucle abierto libera. Diseñá tus ciclos conscientemente.',author:'Teoría de control'},
  {cat:'Filosofía',text:'Cada día es una pequeña vida: cada despertar, un pequeño nacimiento; cada sueño, una pequeña muerte.',author:'Schopenhauer'},
  {cat:'Física',text:'Una onda interfiere con otra: suma o se cancela. Tus hábitos interfieren entre sí — alinealos.',author:'Mecánica ondulatoria'},
  {cat:'Autorrealización',text:'Si tenés tiempo para criticar a otros, tenés tiempo para mejorar vos.',author:'Corina OS'},
  {cat:'Estoicismo',text:'Confundí paz con mediocridad y paciencia con estancamiento. No son iguales.',author:'Corina OS'},
  {cat:'Ciencias',text:'La longevidad no solo es genética — 80% es estilo de vida. Vos controlás más de lo que creés.',author:'Epidemiología'},
  {cat:'Matemática',text:'Un algoritmo de ordenamiento garantiza orden eventual. La consistencia vence a la velocidad.',author:'Computación'},
  {cat:'Filosofía',text:'El mayor regalo que podés darle a alguien es tu tiempo. El más caro también.',author:'Corina OS'},
  {cat:'Autorrealización',text:'2027 no es otro año. Es la continuación del sistema que empezaste en 2026. Confía en el proceso.',author:'Corina OS'},
  {cat:'Estoicismo',text:'El que vive bien, muere bien. Así de simple es la filosofía de los estoicos.',author:'Séneca'},
];

// Get phrase for any date (deterministic by day of 2026)
function getPhraseForDate(d) {
  const start = new Date('2026-01-01T00:00:00');
  const diff = Math.floor((d - start) / (1000 * 60 * 60 * 24));
  const idx = ((diff % PHRASES_2026.length) + PHRASES_2026.length) % PHRASES_2026.length;
  return {
    ...PHRASES_2026[idx],
    dayOfYear: diff + 1
  };
}

// ── DEFAULT HABITS (tu rutina real) ──
const HABITS_DEFAULT = [
  {id:'wake',   name:'Despertar + higiene',       time:'5:30–5:50am',  freq:'Diario',      c:'jade'},
  {id:'run',    name:'Correr / ejercicio mañana', time:'5:50–6:45am',  freq:'Lun–Vie',     c:'gold'},
  {id:'bkfast', name:'Desayuno saludable',         time:'6:45–7:00am',  freq:'Diario',      c:'jade'},
  {id:'icpna',  name:'Clases ICPNA inglés',        time:'7:00–8:00am',  freq:'Lun–Vie',     c:'sky'},
  {id:'work',   name:'Trabajo en Ate',             time:'8:00am–5pm',   freq:'Lun–Vie',     c:'jade'},
  {id:'anki',   name:'Anki PMP/TOEFL/GRE',        time:'Transporte',   freq:'Diario',      c:'gold'},
  {id:'snack',  name:'Snack + descanso',           time:'5:00–5:15pm',  freq:'Diario',      c:'jade'},
  {id:'gym',    name:'Gym SmartFit',               time:'6:00–7:00pm',  freq:'Lun/Mar/Jue', c:'crimson'},
  {id:'pole',   name:'Pole Dance',                 time:'8:00–10:00pm', freq:'Miércoles',   c:'crimson'},
  {id:'pool',   name:'Piscina Videna',             time:'9:00–10:00pm', freq:'Viernes',     c:'sky'},
  {id:'dance',  name:'Baile / Folklore',           time:'3:00–8:00pm',  freq:'Sáb/Dom',     c:'gold'},
  {id:'toefl',  name:'Estudio TOEFL',              time:'1:00–2:00pm',  freq:'Diario',      c:'sky'},
  {id:'pmp',    name:'Estudio PMP',                time:'10:00–11am',   freq:'Sáb/Dom',     c:'gold'},
  {id:'gre',    name:'Estudio GRE',                time:'1:00–2:30pm',  freq:'Lun/Mié/Jue', c:'violet'},
  {id:'maestria',name:'Maestría ESAN virtual',     time:'7:00–10:30pm', freq:'Lun/Jue',     c:'violet'},
  {id:'read',   name:'Leer 10 páginas',            time:'5:15–5:30pm',  freq:'Diario',      c:'jade'},
  {id:'meal',   name:'Meal prep',                  time:'10am–12pm',    freq:'Dom/Lun',     c:'jade'},
  {id:'misa',   name:'Misa',                       time:'8:00–9:00am',  freq:'Domingo',     c:'gold'},
  {id:'plan',   name:'Planificar semana',          time:'10:00–11pm',   freq:'Semanal',     c:'gold'},
  {id:'etfinv', name:'Aporte ETF VOO',             time:'Día 25',       freq:'Día 25',      c:'sky'},
  {id:'sleep',  name:'Dormir 7.5h',                time:'10:30–11pm',   freq:'Diario',      c:'jade'},
];

// ── CONTENT PLANNER OWNERS ──
const OWNERS = [
  {id:'corina',    name:'Corina · Hábitos & Superación', icon:'🐉', color:'#d4a843'},
  {id:'shakira',   name:'Shakira · Contenido Gato',      icon:'🐱', color:'#2ecfa0'},
  {id:'audio',     name:'Audio Electrónica · Negocio',   icon:'🔊', color:'#4090e8'},
  {id:'flores',    name:'Manos que Florecen · Flores',   icon:'🌸', color:'#e04060'},
];

// ── MILESTONES ──
const MILESTONES_DEF = [
  {id:'m0',when:'ABR–MAY 2026',title:'Base del sistema activa',status:'now',pct:15,desc:'Make.com + Buffer · Notion offline · Pagos automáticos · Renta4 abierta · CS50P iniciado'},
  {id:'m1',when:'JUN–JUL 2026',title:'ETF + 1K seguidores LinkedIn',status:'soon',pct:0,desc:'S/15K en VOO (DCA) · Google AI Essentials · 1,000 seg. LinkedIn'},
  {id:'m2',when:'AGO–OCT 2026',title:'Maestría finalizada + charla',status:'soon',pct:0,desc:'Maestría ESAN · S/1,740 liberados · Primera charla pagada · TOEFL programado'},
  {id:'m3',when:'NOV–DIC 2026',title:'Airbnb activo + S/10K/mes',status:'soon',pct:0,desc:'Depa La Victoria Airbnb → S/2,600/mes · Python intermedio · 5K seguidores'},
  {id:'m4',when:'2027 Q1–Q2',title:'Primer ingreso remoto USD',status:'soon',pct:0,desc:'Upwork/Torre.co · Inglés B2 · ETF S/30K+'},
  {id:'m5',when:'2027 Q3–2028',title:'Remoto full-time + hacienda',status:'soon',pct:0,desc:'$2,500–4,000 USD/mes · Starlink · 10K seguidores'},
  {id:'m6',when:'2028–2029',title:'Libertad total + hacienda',status:'soon',pct:0,desc:'Hacienda + Starlink · ETF S/80K+ · Airbnb doble · Italia/China · Shakira 🐱'},
];

// ── SKILLS ──
const SKILLS_DEF = [
  {id:'python',name:'Python / programación',base:45,c:'#2ecfa0'},
  {id:'ingles',name:'Inglés (nivel actual)',base:55,c:'#d4a843'},
  {id:'ia',    name:'IA / ML conceptos',   base:25,c:'#4090e8'},
  {id:'make',  name:'Make.com / automatiz',base:35,c:'#9060e0'},
  {id:'pm',    name:'Gestión proyectos PM',base:80,c:'#2ecfa0'},
  {id:'mec',   name:'Ing. mecatrónica',    base:85,c:'#d4a843'},
  {id:'cont',  name:'Contenido / redes',   base:30,c:'#e04060'},
  {id:'fin',   name:'Finanzas/inversiones',base:40,c:'#4090e8'},
];

// ── PLANNER SEMANAL ──
const PLANNER = [
  {t:'5:30',d:['🌅 Despertar','🌅 Despertar','🌅 Despertar','🌅 Despertar','🌅 Despertar','😴 +1h','⛪ Misa 8am'],c:['pw','pw','pw','pw','pw','ps','pg']},
  {t:'6:00',d:['🏃 Correr','🏃 Correr','🏃 Correr','🏃 Correr','🏃 Correr','🏃 Gym','🏃 Gym'],c:['pw','pw','pw','pw','pw','pw','pw']},
  {t:'7:00',d:['📚 ICPNA','📚 ICPNA','📚 ICPNA','📚 ICPNA','📚 ICPNA','📖 TOEFL','📅 Planif.'],c:['pv','pv','pv','pv','pv','pv','pb-batch']},
  {t:'8:00',d:['⚙️ WORK','⚙️ WORK','⚙️ WORK','⚙️ WORK','⚙️ WORK','📖 PMP','📖 GRE'],c:['pw','pw','pw','pw','pw','pg','pv']},
  {t:'12:00',d:['📹 Grabar','📹 Grabar','📹 Grabar','📹 Grabar','📹 Grabar','🍽 Almuerzo','🍽 Almuerzo'],c:['pw','pw','pw','pw','pw','ps','ps']},
  {t:'1:00',d:['📖 TOEFL','📖 TOEFL','📖 PMP','📖 GRE','📖 PMP','🇮🇹 Italiano','📋 Negocio'],c:['pv','pv','pg','pv','pg','pw','pb2']},
  {t:'5:00',d:['🍎 Snack','🍎 Snack','🍎 Snack','🍎 Snack','🍎 Snack','💃 Folklore','💃 Folklore'],c:['pw','pw','pw','pw','pw','pg','pg']},
  {t:'6:00',d:['🏋️ Gym','🏋️ Gym','🏋️ Gym→Pole','🏋️ Gym','🎨 Editar','💃 Baile','💃 Baile'],c:['pr','pr','pr','pr','pg','pg','pg']},
  {t:'7:00',d:['🎓 Maestría','📖 GRE','🎪 Pole','🎓 Maestría','📖 GRE','💻 Influencer','—'],c:['pv','pv','pr','pv','pv','pb2','pe']},
  {t:'9:00',d:['🎓 Maestría','📖 PMP','🎪 Pole','🎓 Maestría','🏊 Piscina','📖 PMP','🀄 Chino'],c:['pv','pg','pr','pv','ps','pg','pb2']},
  {t:'10:00',d:['📋 Plan','💻 Influencer','—','📋 Plan','🏊 Piscina','📚 Leer','📚 Leer'],c:['pg','pb2','pe','pg','ps','pw','pw']},
];

const DAYS_WEEK = ['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'];
const COLORS = {
  jade:'var(--jade)', gold:'var(--gold)', crimson:'var(--crimson)',
  sky:'var(--sky)', violet:'var(--violet)', fire:'var(--fire)'
};
const TAG_COLORS = {
  general:'var(--m2)', finanzas:'var(--gold)', estudio:'var(--jade)',
  habitos:'var(--crimson)', contenido:'var(--violet)', personal:'var(--sky)'
};
